### PR TITLE
Fix some bugs: support micro-batched denoising

### PR DESCRIPTION
**Pull request by Light-of-Hers**
Previous version neglected the following case, where sub-prompts are packed into several micro-batches and fed into diffusion-model：
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8/modules/sd_samplers_kdiffusion.py#L124-L138
```python
        else:
            x_out = torch.zeros_like(x_in)
            batch_size = batch_size*2 if shared.batch_cond_uncond else batch_size
            for batch_offset in range(0, tensor.shape[0], batch_size):
                a = batch_offset
                b = min(a + batch_size, tensor.shape[0])


                if not is_edit_model:
                    c_crossattn = [tensor[a:b]]
                else:
                    c_crossattn = torch.cat([tensor[a:b]], uncond)


                x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})


            x_out[-uncond.shape[0]:] = self.inner_model(x_in[-uncond.shape[0]:], sigma_in[-uncond.shape[0]:], cond={"c_crossattn": [uncond], "c_concat": [image_cond_in[-uncond.shape[0]:]]})
```
This PR adds support for such case. 

By the way, original code may have a bug of processing text-model-encoder: "This code evaluated twice in get_learned_conditioning." should be "This code evaluated X times in get_learned_conditioning, where X is the number of loaded loras":
https://github.com/opparco/stable-diffusion-webui-composable-lora/blob/11fe4cac71090c4069109179befb9a663d7249d9/composable_lora.py#L63-L83

Here is a example showing the effect of this fix:
Generate Info:
```
masterpiece, best quality, 3girls, outdoors, night, holding hands, looking at another, from side, looking away, eye contact, facing another, faceoff,
AND masterpiece, best quality, 3girls, upper body,  <lora:asoulBella_v10:1>, purple eyes, purple hair, navel, ribbon, holding hands, looking at another, from side, looking away, eye contact, facing another,
AND masterpiece, best quality, 3girls, upper body,  <lora:asoulEileenpicoLORA_v10:1>, blue eyes, white long hair, holding hands, looking at another, from side, looking away, eye contact, facing another,
AND masterpiece, best quality, 3girls, upper body,  <lora:chracterYukino_v10:1>, blue eyes, white long hair, holding hands, looking at another, from side, looking away, eye contact, facing another,
Negative prompt: ugly, huge eyes, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4),(deformed fingers:1.2),(long fingers:1.2), (bad-artist-anime), bad-artist, bad hand,
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 661846343, Size: 768x512, Model hash: 6e430eb514, Denoising strength: 0.5, Clip skip: 2, ENSD: 31337, Latent Couple: "divisions=1:1,1:3,1:3,1:3 positions=0:0,0:0,0:1,0:2 weights=0.2,0.8,0.8,0.8 end at step=20", Hires upscale: 2, Hires steps: 10, Hires upscaler: SwinIR_4x
```
Before:
image
After:
image

### CODE REVIEW

**Comment by opparco** [comment]
@Light-of-Hers 
thanks for the report.
I probably already made a fix for the same issue. 92c531406504ac610a3e39699a82eafe12fec745

**Comment by Light-of-Hers** [comment]
> @Light-of-Hers thanks for the report. I probably already made a fix for the same issue. [92c5314](https://github.com/opparco/stable-diffusion-webui-composable-lora/commit/92c531406504ac610a3e39699a82eafe12fec745)

There's might be still a little problem. When `lora_layer_name.endswith("_11_mlp_fc2")`, there's `text_model_encoder_counter += 1` for every `lora in lora.loaded_loras` with the same `res` (each `res` corresponds to a sub-prompt), then there might be some mismatch between the sub-prompt and the LoRAs applied to it.

https://github.com/opparco/stable-diffusion-webui-composable-lora/blob/5c1ca9c57c8b41b0bb6802c025b90238c909061a/composable_lora.py#L61
https://github.com/opparco/stable-diffusion-webui-composable-lora/blob/5c1ca9c57c8b41b0bb6802c025b90238c909061a/composable_lora.py#L115-L134

For example, with the following generate info: 
```
masterpiece, best quality, 3girls, outdoors, night, holding hands, looking at another, from side, looking away, eye contact, facing another, faceoff,
AND masterpiece, best quality, 3girls, upper body,  <lora:asoulBella_v10:1>, purple eyes, purple hair, navel, ribbon, holding hands, looking at another, from side, looking away, eye contact, facing another,
AND masterpiece, best quality, 3girls, upper body,  <lora:asoulEileenpicoLORA_v10:1>, blue eyes, white long hair, holding hands, looking at another, from side, looking away, eye contact, facing another,
AND masterpiece, best quality, 3girls, upper body,  <lora:chracterYukino_v10:1>, blue eyes, white long hair, holding hands, looking at another, from side, looking away, eye contact, facing another,
Negative prompt: ugly, huge eyes, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4),(deformed fingers:1.2),(long fingers:1.2), (bad-artist-anime), bad-artist, bad hand,
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 661846343, Size: 768x512, Model hash: 6e430eb514, Denoising strength: 0.5, Clip skip: 2, ENSD: 31337, Latent Couple: "divisions=1:1,1:3,1:3,1:3 positions=0:0,0:0,0:1,0:2 weights=0.2,0.8,0.8,0.8 end at step=20", Hires upscale: 2, Hires steps: 10, Hires upscaler: SwinIR_4x
```
The generated image with [92c5314](https://github.com/opparco/stable-diffusion-webui-composable-lora/commit/92c531406504ac610a3e39699a82eafe12fec745) is (obviously all the LoRAs are shared among these three girls):
image
While a more correct version should be:
image

**Comment by opparco** [comment]
@Light-of-Hers 
your code is correct. it will be merged.

**Comment by Light-of-Hers** [comment]
> @Light-of-Hers your code is correct. it will be merged.

Thanks. I'm glad to make contribution to your extension, which help me a lot.

**Comment by Ahmedmjo** [comment]
incorrect hands, extra limbs, extra fingers, fused fingers, missing facial features, low quality, bad quality, bad anatomy, Missing limbs, missing fingers, scary, ugly

**Pull request closed without merging**
